name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: zhangkong/schedulerz.manager.api
          dockerfile: ./src/SchedulerZ.Manager.API/Dockerfile